// Generated by https://pagedraw.io/pages/8673
import React from 'react';
import './form_guest.css';

function render() {
    return <div className="form_guest-form_guest-5">
        <div className="form_guest-0">
            <div className="form_guest-rectangle-8">
                <div className="form_guest-0-0-0">
                    <div className="form_guest-text-1">
                        { this.props.greeting }
                    </div>
                </div>
                <div className="form_guest-0-0-1">
                    <div className="form_guest-text-0">
                        Thanks for sending us your test
                    </div>
                </div>
                <div className="form_guest-0-0-2">
                    <input type="text" placeholder="Full Name" className="form_guest-text_input-6" /> 
                </div>
                <div className="form_guest-0-0-3">
                    <input type="text" placeholder="Message" className="form_guest-text_input-0" /> 
                </div>
                <div className="form_guest-0-0-4">
                    <div className="form_guest-rectangle_2">
                        <div className="form_guest-0-0-4-0-0">
                            <div className="form_guest-text_2">Send Message</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}