// Generated by https://pagedraw.io/pages/8989
import React from 'react';
import './hello_world.css';

function render() {
    return <div className="hello_world-hello_world-4">
        <div className="hello_world-0">
            <div className="hello_world-text_2">
                Hi this is my first project
            </div>
        </div>
        <div className="hello_world-1">
            <div className="hello_world-rectangle-4">
                <div className="hello_world-1-0-0">
                    <input type="text" placeholder="You Name" onChange={this.props.handleChange} className="hello_world-text_input-9" /> 
                </div>
                <div className="hello_world-1-0-1">
                    <div onClick={this.props.handleClick} className="hello_world-rectangle_2">
                        <div className="hello_world-1-0-1-0-0">
                            <div className="hello_world-text-9">Submit</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}